### ISSUE TITLE
Some Feedbacks

### ISSUE THREAD

**Issue by Muyangmin** [t-kameyama/intellij-db-to-kotlin-class#3]
Hi @t-kameyama , thank you for developing this plugin, which has saved me a lot of development time! 👏

Here is some feedback from using it over the past few days, I hope it helpful:

* After restarting the IDE, settings such as postfix and annotation in Preferences are not saved and need to be re-input (I think this is a bug);
* When the plugin restores the data class name based on the table name, it will automatically remove the plural at the end of the table name. For example, "summaries" will become "summary", which I think is a good design. However, there is a funny exception where "address" will be processed as "addres".  Maybe it's a hardly-to-find bug to me without IDEA's spell check🤣
* Could  you please add a setting to automatically convert them to camel case? For example, the database field `last_updated_date` and `LastUpdateDate` is currently processed as `lastupdateddate`, which is not very readable and requires manually changing the letter case. If it could be automatically processed as `lastUpdatedDate`, that would be great😍

Thanks for reading and I wil continually provide further feedback if you not mind~

**Comment by t-kameyama** [comment]
@Muyangmin 
Thanks for your feedback. Version 0.3.0 has been released. Try it.
https://plugins.jetbrains.com/plugin/18611-database-to-kotlin-class/versions/stable/330797
